% figure3_tf_itemdistance_plot.m - Plot beta power scaling with item distance
%
% This script loads pre-calculated TF power data organized by item distance
% (angular distance between memory items) and creates Figure 3 from the paper.
%
% KEY FINDING:
%   Beta power (15-25Hz) at central channels scales with item distance
%   on Switch trials: larger switches → greater beta desynchronization.
%   Theta power does not show this scaling effect.
%
% INPUTS:
%   - results/Study12_Figure3_TF_ItemDistance_Results_*.mat
%     (generated by figure3_tf_itemdistance_calculate.m)
%
% OUTPUTS:
%   - Figure 3 panels (saved as PNG, EPS, PDF)
%   - Statistical results printed to console
%
% Author: Nicholas E. Myers
% Refactored for GitHub: 2026
% For: Myers, Stokes, & Muhle-Karbe (2026) J. Neuroscience

clearvars;
close all;
clc;

%% 1. CONFIGURATION AND DATA LOADING

% Load paths
paths = config();

% Subject information
subject_pairs = [05 10 11 12 13 14 15; 
                 28 23 22 24 34 42 41];
experiment_list = [ones(1,20)*1 ones(1,30)*2];

% Find most recent results file
results_pattern = fullfile(paths.results, 'Study12_Figure3_TF_ItemDistance_Results_*.mat');
files = dir(results_pattern);
if isempty(files)
    error('No results file found. Run figure3_tf_itemdistance_calculate.m first.');
end

[~, idx] = max([files.datenum]);
results_file = fullfile(files(idx).folder, files(idx).name);
fprintf('Loading results from: %s\n', results_file);
load(results_file);

% Extract data
tf_by_distance = output.tfmutempdist;
regression_betas = output.betamat_templatedist;
time_tf = output.timeTF;
frequencies = output.freq;
unique_distances = output.utemplatedist;

%% 2. MERGE DATA FROM SUBJECTS IN BOTH EXPERIMENTS

fprintf('Merging data from subjects in both experiments...\n');

tf_by_distance_merged = merge_experiments(tf_by_distance, subject_pairs, experiment_list);
regression_betas_merged = merge_experiments(regression_betas, subject_pairs, experiment_list);

num_subjects = size(tf_by_distance_merged, 1);
fprintf('Final sample: %d subjects\n', num_subjects);

%% 3. DEFINE PLOTTING PARAMETERS

SetupPlotting();

% Colors
color_switch = [0.20, 0.35, 0.80];  % blue
color_repeat = [0.50, 0.50, 0.50];  % grey
condition_colors = [color_switch; color_repeat];

% Time and frequency windows for analysis
beta_time_window = [0.4, 0.8];  % seconds
beta_freq_band = [15, 25];  % Hz
theta_freq_band = [4, 8];  % Hz

%% 4. FIGURE: BETA POWER BY ITEM DISTANCE

fprintf('\nCreating Figure: Beta power by item distance...\n');

fig_beta = figure('Position', [50, 50, 1250, 750]);

%% 4.1 Panel A: Beta power by item distance (Switch vs. Repeat)

subplot(4, 4, [1, 5]);

% Extract beta power in time-frequency window
beta_freq_idx = frequencies >= beta_freq_band(1) & frequencies <= beta_freq_band(2);
beta_time_idx = time_tf >= beta_time_window(1) & time_tf <= beta_time_window(2);

% Average over central channels, beta frequency, and time window
beta_power = squeeze(mean(mean(mean(...
    tf_by_distance_merged(:, output.centralchans, beta_freq_idx, beta_time_idx, :, :), ...
    2), 3), 4));

hold on;
patch_handles = [];

for i_cond = 1:2  % Switch and Repeat only
    % Fit linear regression
    regression_coeffs = fit_linear_regression(...
        unique_distances, beta_power(:, :, i_cond));
    
    % Plot regression line with error
    patch_handles(i_cond) = plot_regression_with_error(...
        regression_coeffs, unique_distances, condition_colors(i_cond, :));
    
    % Plot data points
    plot_points_with_errors(...
        beta_power(:, :, i_cond), unique_distances', ...
        condition_colors(i_cond, :), 25);
end

% Format
format_axes_standard();
ylim([-0.75, 0.25]);
set(gca, 'YTick', -0.75:0.25:0.25);
set(gca, 'XTick', round(unique_distances));
ylabel('Power (dB)');
xlim([0, 90]);
title('15-25Hz', 'FontAngle', 'italic', 'FontWeight', 'normal');

% Statistical tests
print_item_distance_statistics('Beta Power', beta_power, unique_distances);

%% 4.2 Panel B: Time-frequency map of item distance effect

subplot(4, 4, [2, 3, 4, 6, 7, 8]);

% Calculate regression coefficient (effect of item distance)
% Use first regressor (template distance)
regressor_idx = 1;  % template distance is first regressor

% Extract Switch trial regression betas
switch_betas = regression_betas_merged(:, :, :, :, regressor_idx, 1);  % Switch condition

% Average over central channels
central_betas = squeeze(mean(switch_betas(:, output.centralchans, :, :), 2));

% Calculate mean across subjects (convert to % change per 10 degrees)
mean_betas = squeeze(mean(central_betas, 1)) * 100;

% Statistical test
[~, p_values, ~, stats] = ttest(central_betas);
p_corrected = squeeze(p_values);

% Plot
imagesc(time_tf, frequencies, mean_betas);
set(gca, 'YDir', 'normal');
hold on;

% Mark significant regions
contour(time_tf, frequencies, p_corrected < 0.05, 1, ...
       'LineColor', 'k', 'LineWidth', 2);

% Format
colormap(cbrewer('div', 'RdBu', 64));
colorbar;
caxis([-1, 1] * max(abs(mean_betas(:))));
xlim([-0.25, 1.5]);
ylim([2, 40]);
xlabel('Time from cue (s)');
ylabel('Frequency (Hz)');
title('Switch: Item Distance Effect (% per 10°)');

% Reference lines
plot([0, 0], ylim, 'k--', 'LineWidth', 1);
plot([0.8, 0.8], ylim, 'k--', 'LineWidth', 1);

%% 4.3 Panel C: Topography of beta effect

subplot(4, 4, [9, 10]);

% Average over beta band and time window
beta_freq_idx = frequencies >= beta_freq_band(1) & frequencies <= beta_freq_band(2);
beta_time_idx = time_tf >= beta_time_window(1) & time_tf <= beta_time_window(2);

topo_data = squeeze(mean(mean(mean(...
    switch_betas(:, :, beta_freq_idx, beta_time_idx), 3), 4), 1)) * 100;

% Simple topography plot (placeholder for FieldTrip topoplot)
plot_topography(topo_data, output.centralchans);
title(sprintf('Beta Effect (%.0f-%.0f Hz)', beta_freq_band(1), beta_freq_band(2)));

%% 4.4 Panel D: Frequency profile

subplot(4, 4, [11, 12]);

% Average over time window, across subjects and channels
freq_data = squeeze(mean(mean(mean(central_betas(:, :, beta_time_idx), 3), 1), 1)) * 100;
freq_sem = squeeze(std(mean(mean(central_betas(:, :, beta_time_idx), 3), 1), [], 1)) * ...
          100 / sqrt(num_subjects);

% Plot
plot_with_error_patch(frequencies, freq_data, freq_sem, color_switch);

% Mark significant frequencies
sig_freq = squeeze(any(p_corrected(:, beta_time_idx) < 0.05, 2));
hold on;
plot(frequencies(sig_freq), ones(nnz(sig_freq), 1) * min(freq_data), ...
    'k.', 'MarkerSize', 10);
plot([0, 45], [0, 0], 'k--', 'LineWidth', 1);

% Format
xlim([2, 40]);
xlabel('Frequency (Hz)');
ylabel('Effect (% per 10°)');
title('Frequency Profile');

%% 4.5 Panel E: Time course

subplot(4, 4, [13, 14]);

% Average over beta band
beta_freq_idx = frequencies >= beta_freq_band(1) & frequencies <= beta_freq_band(2);
time_data = squeeze(mean(mean(mean(central_betas(:, :, beta_freq_idx, :), 3), 2), 1)) * 100;
time_sem = squeeze(std(mean(mean(central_betas(:, :, beta_freq_idx, :), 3), 2), [], 1)) * ...
          100 / sqrt(num_subjects);

% Plot
plot_with_error_patch(time_tf, time_data, time_sem, color_switch);

% Mark significant timepoints
sig_time = squeeze(any(p_corrected(beta_freq_idx, :) < 0.05, 1));
hold on;
plot(time_tf(sig_time), ones(nnz(sig_time), 1) * min(time_data), ...
    'k.', 'MarkerSize', 10);
plot([0, 0], ylim, 'k--', 'LineWidth', 1);
plot([0.8, 0.8], ylim, 'k--', 'LineWidth', 1);
plot(xlim, [0, 0], 'k--', 'LineWidth', 1);

% Format
xlim([-0.25, 1.5]);
xlabel('Time from cue (s)');
ylabel('Effect (% per 10°)');
title('Time Course (Beta Band)');

% Save figure
save_figure(fig_beta, paths, 'Figure3', 'Beta-ItemDistance');

%% 5. FIGURE: THETA POWER BY ITEM DISTANCE (FOR COMPARISON)

fprintf('\nCreating Figure: Theta power by item distance...\n');

fig_theta = figure('Position', [100, 100, 800, 600]);

%% 5.1 Theta power by item distance

subplot(2, 2, 1);

% Extract theta power
theta_freq_idx = frequencies >= theta_freq_band(1) & frequencies <= theta_freq_band(2);
theta_time_idx = time_tf >= beta_time_window(1) & time_tf <= beta_time_window(2);

theta_power = squeeze(mean(mean(mean(...
    tf_by_distance_merged(:, output.frontalchans, theta_freq_idx, theta_time_idx, :, :), ...
    2), 3), 4));

hold on;
for i_cond = 1:2
    regression_coeffs = fit_linear_regression(...
        unique_distances, theta_power(:, :, i_cond));
    
    plot_regression_with_error(...
        regression_coeffs, unique_distances, condition_colors(i_cond, :));
    
    plot_points_with_errors(...
        theta_power(:, :, i_cond), unique_distances', ...
        condition_colors(i_cond, :), 25);
end

format_axes_standard();
set(gca, 'XTick', round(unique_distances));
ylabel('Power (dB)');
xlabel('Item Distance (°)');
xlim([0, 90]);
title('4-8Hz (Frontal Channels)');

% Statistical tests
print_item_distance_statistics('Theta Power', theta_power, unique_distances);

% Save figure
save_figure(fig_theta, paths, 'Figure3', 'Theta-ItemDistance');

fprintf('\n=== Plotting Complete! ===\n');

%% HELPER FUNCTIONS

function merged_data = merge_experiments(data, subject_pairs, experiment_list)
    % MERGE_EXPERIMENTS - Average data from subjects in both experiments
    merged_data = Switch_MergeExperiments(data, subject_pairs, experiment_list, false, +Inf);
end

function betas = fit_linear_regression(x_values, y_data)
    % FIT_LINEAR_REGRESSION - Fit linear model to each subject
    num_subjects = size(y_data, 1);
    betas = zeros(num_subjects, 2);
    
    for i_sub = 1:num_subjects
        y = y_data(i_sub, :)';
        X = [ones(length(x_values), 1), x_values(:)];
        betas(i_sub, :) = X \ y;
    end
end

function h = plot_regression_with_error(betas, x_values, color)
    % PLOT_REGRESSION_WITH_ERROR - Plot regression line with error patch
    intercepts = betas(:, 1);
    slopes = betas(:, 2);
    predicted_lines = intercepts + slopes .* x_values';
    h = plot_with_error_patch(x_values, mean(predicted_lines, 1), ...
        std(predicted_lines, [], 1) / sqrt(size(betas, 1)), color);
end

function h = plot_with_error_patch(x, y, sem, color)
    % PLOT_WITH_ERROR_PATCH - Plot line with shaded error region
    hold on;
    x_patch = [x(:); flipud(x(:))];
    y_patch = [y(:) + sem(:); flipud(y(:) - sem(:))];
    h = patch(x_patch, y_patch, color, 'FaceAlpha', 0.25, 'EdgeColor', 'none');
    plot(x, y, 'Color', color, 'LineWidth', 2);
end

function plot_points_with_errors(data, x_values, color, marker_size)
    % PLOT_POINTS_WITH_ERRORS - Plot data points with error bars
    mean_values = mean(data, 1, 'omitnan');
    sem_values = std(data, [], 1, 'omitnan') / sqrt(size(data, 1));
    errorbar(x_values, mean_values, sem_values, 'o', ...
            'Color', color, 'MarkerFaceColor', color, ...
            'MarkerSize', marker_size/5, 'LineWidth', 1.5, 'CapSize', 0);
end

function format_axes_standard()
    % FORMAT_AXES_STANDARD - Apply standard axis formatting
    box off;
    ax = gca;
    ax.TickDir = 'out';
    ax.LineWidth = 1;
end

function plot_topography(data, highlight_channels)
    % PLOT_TOPOGRAPHY - Simple topographic visualization
    % Note: For publication, use FieldTrip's ft_topoplotTFR
    imagesc(reshape(data, [], 1)');
    colormap(cbrewer('div', 'RdBu', 64));
    colorbar;
    caxis([-1, 1] * max(abs(data(:))));
    axis off;
end

function print_item_distance_statistics(measure_name, data, x_values)
    % PRINT_ITEM_DISTANCE_STATISTICS - Print regression statistics
    fprintf('\n\n%s - Effect of Item Distance:\n', measure_name);
    fprintf('----------------------------------------\n');
    
    for i_cond = 1:2
        betas = fit_linear_regression(x_values, data(:, :, i_cond));
        
        mean_slope = mean(betas(:, 2));
        sem_slope = std(betas(:, 2)) / sqrt(size(betas, 1));
        
        [~, p_val, ~, t_stat] = ttest(betas(:, 2));
        d = mean(betas(:, 2)) / std(betas(:, 2));
        
        cond_name = {'Switch', 'Repeat'};
        fprintf('  %s: %.3f ± %.3f per 10°, t(%d)=%.2f, p=%.4g, d=%.2f\n', ...
               cond_name{i_cond}, mean_slope*100, sem_slope*100, ...
               t_stat.df, t_stat.tstat, p_val, d);
    end
    
    % Test difference
    betas_all = zeros(size(data, 1), 2, 2);
    for i_cond = 1:2
        betas_all(:, :, i_cond) = fit_linear_regression(x_values, data(:, :, i_cond));
    end
    
    [~, p_val, ~, t_stat] = ttest(betas_all(:, 2, 1), betas_all(:, 2, 2));
    d = mean(betas_all(:, 2, 1) - betas_all(:, 2, 2)) / std(betas_all(:, 2, 1) - betas_all(:, 2, 2));
    
    fprintf('  Switch vs Repeat: t(%d)=%.2f, p=%.4g, d=%.2f\n', ...
           t_stat.df, t_stat.tstat, p_val, d);
end

function save_figure(fig_handle, paths, subfolder, filename)
    % SAVE_FIGURE - Save figure in multiple formats
    figure_dir = fullfile(paths.results, 'figures', subfolder);
    if ~exist(figure_dir, 'dir')
        mkdir(figure_dir);
    end
    
    timestamp = datestr(now, 'yyyymmdd-HHMM');
    full_filename = fullfile(figure_dir, sprintf('%s_%s', filename, timestamp));
    
    print(fig_handle, '-dpng', full_filename);
    print(fig_handle, '-depsc2', full_filename, '-painters');
    print(fig_handle, '-dpdf', full_filename, '-painters');
    
    fprintf('Saved: %s\n', full_filename);
end
