% figure4_decoding_correlation_plot.m - Plot beta-decoding correlations
%
% This script loads pre-calculated decoding and beta power data and
% generates Figure 4 from the paper, showing the relationship between
% beta power and memory decoding fidelity.
%
% KEY FINDING:
%   Lower beta power (greater desynchronization) predicts stronger decoding
%   of the newly prioritized (active) memory item. This suggests beta
%   desynchronization tracks the quality of the updated memory representation.
%
% INPUTS:
%   - results/Figure4_Decoding_BetaCorrelation_Results_*.mat
%     (generated by figure4_decoding_correlation_calculate.m)
%
% OUTPUTS:
%   - Figure 4 panels (saved as PNG, EPS, PDF)
%   - Statistical results printed to console
%
% Author: Nicholas E. Myers
% Refactored for GitHub: 2026
% For: Myers, Stokes, & Muhle-Karbe (2026) J. Neuroscience

clearvars;
close all;
clc;

%% 1. CONFIGURATION AND DATA LOADING

% Load paths
paths = config();

% Subject pairs
subject_pairs = [05 10 11 12 13 14 15; 
                 28 23 22 24 34 42 41];
experiment_list = [ones(1,20)*1 ones(1,30)*2];

% Find most recent results file
results_pattern = fullfile(paths.results, 'Figure4_Decoding_BetaCorrelation_Results_*.mat');
files = dir(results_pattern);
if isempty(files)
    error('No results file found. Run figure4_decoding_correlation_calculate.m first.');
end

[~, idx] = max([files.datenum]);
results_file = fullfile(files(idx).folder, files(idx).name);
fprintf('Loading results from: %s\n', results_file);
load(results_file);

% Extract data
correlations = output.correlation;
time_windows = output.time_windows;

%% 2. MERGE DATA FROM SUBJECTS IN BOTH EXPERIMENTS

fprintf('Merging data from subjects in both experiments...\n');

correlations_merged = merge_experiments(correlations, subject_pairs, experiment_list);

num_subjects = size(correlations_merged, 1);
fprintf('Final sample: %d subjects\n', num_subjects);

%% 3. DEFINE PLOTTING PARAMETERS

SetupPlotting();

% Colors
color_active_to_active = [0.20, 0.35, 0.80];   % blue (decode active, test active)
color_active_to_latent = [0.80, 0.35, 0.20];   % red (decode active, test latent)
color_latent_to_active = [0.35, 0.80, 0.20];   % green (decode latent, test active)
color_latent_to_latent = [0.50, 0.50, 0.50];   % grey (decode latent, test latent)

condition_colors = [color_active_to_active; 
                   color_active_to_latent;
                   color_latent_to_active;
                   color_latent_to_latent];

condition_labels = {'Active→Active', 'Active→Latent', 'Latent→Active', 'Latent→Latent'};

%% 4. FIGURE: BETA-DECODING CORRELATIONS OVER TIME

fprintf('\nCreating Figure: Beta-decoding correlations...\n');

fig_correlation = figure('Position', [50, 50, 1200, 400]);

%% 4.1 Panel A: Correlation time course (all conditions)

subplot(1, 3, 1);
hold on;

for i_train = 1:2
    for i_test = 1:2
        cond_idx = (i_train - 1) * 2 + i_test;
        
        % Extract correlations for this condition
        corr_data = squeeze(correlations_merged(:, :, i_train, i_test));
        
        % Calculate mean and SEM
        mean_corr = mean(corr_data, 1, 'omitnan');
        sem_corr = std(corr_data, [], 1, 'omitnan') / sqrt(num_subjects);
        
        % Plot
        plot_with_error_patch(time_windows, mean_corr, sem_corr, ...
            condition_colors(cond_idx, :));
    end
end

% Format
plot([min(time_windows), max(time_windows)], [0, 0], 'k--', 'LineWidth', 1);
plot([0, 0], ylim, 'k--', 'LineWidth', 1);  % Cue onset
plot([0.8, 0.8], ylim, 'k--', 'LineWidth', 1);  % Probe onset

xlabel('Time from cue (s)');
ylabel('Beta-Decoding Correlation (r)');
title('All Conditions');
legend(condition_labels, 'Location', 'best', 'Box', 'off');
xlim([min(time_windows), max(time_windows)]);

%% 4.2 Panel B: Focus on active item decoding

subplot(1, 3, 2);
hold on;

% Active→Active (main effect)
corr_active_active = squeeze(correlations_merged(:, :, 1, 1));
mean_corr = mean(corr_active_active, 1, 'omitnan');
sem_corr = std(corr_active_active, [], 1, 'omitnan') / sqrt(num_subjects);

plot_with_error_patch(time_windows, mean_corr, sem_corr, color_active_to_active);

% Statistical significance
[~, p_values] = ttest(corr_active_active);
sig_times = p_values < 0.05;
plot(time_windows(sig_times), ones(nnz(sig_times), 1) * min(mean_corr), ...
    'k.', 'MarkerSize', 10);

% Format
plot([min(time_windows), max(time_windows)], [0, 0], 'k--', 'LineWidth', 1);
plot([0, 0], ylim, 'k--', 'LineWidth', 1);
plot([0.8, 0.8], ylim, 'k--', 'LineWidth', 1);

xlabel('Time from cue (s)');
ylabel('Beta-Decoding Correlation (r)');
title('Active Item Decoding');
xlim([min(time_windows), max(time_windows)]);

%% 4.3 Panel C: Average in cue-probe interval

subplot(1, 3, 3);

% Define cue-probe interval
cue_probe_window = [0.4, 0.8];
time_idx = time_windows >= cue_probe_window(1) & time_windows <= cue_probe_window(2);

% Average correlations in this window
mean_correlations = squeeze(mean(correlations_merged(:, time_idx, :, :), 2));

% Organize for plotting
plot_data = zeros(num_subjects, 4);
plot_data(:, 1) = mean_correlations(:, 1, 1);  % Active→Active
plot_data(:, 2) = mean_correlations(:, 1, 2);  % Active→Latent
plot_data(:, 3) = mean_correlations(:, 2, 1);  % Latent→Active
plot_data(:, 4) = mean_correlations(:, 2, 2);  % Latent→Latent

% Plot
hold on;
for i_cond = 1:4
    x_pos = i_cond;
    
    % Box plot
    boxchart(x_pos * ones(num_subjects, 1), plot_data(:, i_cond), ...
            'BoxFaceColor', condition_colors(i_cond, :), ...
            'MarkerColor', [0 0 0]);
    
    % Mean line
    mean_val = mean(plot_data(:, i_cond), 'omitnan');
    plot(x_pos + [-0.25, +0.25], [mean_val, mean_val], 'k-', 'LineWidth', 2);
    
    % Individual subjects
    for i_sub = 1:num_subjects
        jitter = (rand - 0.5) * 0.2;
        scatter(x_pos + jitter, plot_data(i_sub, i_cond), 25, ...
               'MarkerEdgeColor', [0 0 0], ...
               'MarkerFaceColor', condition_colors(i_cond, :), ...
               'MarkerFaceAlpha', 0.5);
    end
end

% Reference line
plot([0.5, 4.5], [0, 0], 'k--', 'LineWidth', 1);

% Format
xlim([0.5, 4.5]);
set(gca, 'XTick', 1:4, 'XTickLabel', condition_labels, 'XTickLabelRotation', 45);
ylabel('Beta-Decoding Correlation (r)');
title(sprintf('Cue-Probe Interval (%.1f-%.1f s)', ...
      cue_probe_window(1), cue_probe_window(2)));
box off;
ax = gca;
ax.TickDir = 'out';

% Save figure
save_figure(fig_correlation, paths, 'Figure4', 'Beta-Decoding-Correlation');

%% 5. PRINT STATISTICS

fprintf('\n=== Statistical Summary ===\n');

% Test each condition against zero
fprintf('\nCorrelations in Cue-Probe Interval (%.1f-%.1f s):\n', ...
    cue_probe_window(1), cue_probe_window(2));

for i_cond = 1:4
    data = plot_data(:, i_cond);
    mean_val = mean(data, 'omitnan');
    sem_val = std(data, 'omitnan') / sqrt(num_subjects);
    
    [~, p_val, ~, t_stat] = ttest(data);
    d = mean_val / std(data, 'omitnan');
    
    fprintf('  %s: r=%.3f ± %.3f, t(%d)=%.2f, p=%.4g, d=%.2f\n', ...
           condition_labels{i_cond}, mean_val, sem_val, ...
           t_stat.df, t_stat.tstat, p_val, d);
end

% Test difference: Active→Active vs. Latent→Latent
fprintf('\nComparison: Active→Active vs. Latent→Latent:\n');
[~, p_val, ~, t_stat] = ttest(plot_data(:, 1), plot_data(:, 4));
d = mean(plot_data(:, 1) - plot_data(:, 4)) / std(plot_data(:, 1) - plot_data(:, 4));
fprintf('  t(%d)=%.2f, p=%.4g, d=%.2f\n', t_stat.df, t_stat.tstat, p_val, d);

% Test difference: Active→Active vs. Active→Latent
fprintf('\nComparison: Active→Active vs. Active→Latent:\n');
[~, p_val, ~, t_stat] = ttest(plot_data(:, 1), plot_data(:, 2));
d = mean(plot_data(:, 1) - plot_data(:, 2)) / std(plot_data(:, 1) - plot_data(:, 2));
fprintf('  t(%d)=%.2f, p=%.4g, d=%.2f\n', t_stat.df, t_stat.tstat, p_val, d);

fprintf('\n=== Plotting Complete! ===\n');

%% HELPER FUNCTIONS

function merged_data = merge_experiments(data, subject_pairs, experiment_list)
    % MERGE_EXPERIMENTS - Average data from subjects in both experiments
    merged_data = Switch_MergeExperiments(data, subject_pairs, experiment_list, false, +Inf);
end

function plot_with_error_patch(x, y, sem, color)
    % PLOT_WITH_ERROR_PATCH - Plot line with shaded error region
    
    hold on;
    
    % Shaded error region
    x_patch = [x(:); flipud(x(:))];
    y_patch = [y(:) + sem(:); flipud(y(:) - sem(:))];
    patch(x_patch, y_patch, color, 'FaceAlpha', 0.25, 'EdgeColor', 'none');
    
    % Mean line
    plot(x, y, 'Color', color, 'LineWidth', 2);
end

function save_figure(fig_handle, paths, subfolder, filename)
    % SAVE_FIGURE - Save figure in multiple formats
    
    figure_dir = fullfile(paths.results, 'figures', subfolder);
    if ~exist(figure_dir, 'dir')
        mkdir(figure_dir);
    end
    
    timestamp = datestr(now, 'yyyymmdd-HHMM');
    full_filename = fullfile(figure_dir, sprintf('%s_%s', filename, timestamp));
    
    print(fig_handle, '-dpng', full_filename);
    print(fig_handle, '-depsc2', full_filename, '-painters');
    print(fig_handle, '-dpdf', full_filename, '-painters');
    
    fprintf('Saved: %s\n', full_filename);
end
