% figure1_behavior_plot.m - Plot behavioral switch costs and item distance effects
%
% This script loads the behavioral analysis results and generates Figure 1
% from the paper, showing:
%   - Accuracy and RT by trial type (Switch vs. Repeat)
%   - Psychometric curves with swap error modeling
%   - Item distance effects on performance
%
% INPUTS:
%   - results/Study12_Figure1_Behavior_Results_*.mat
%     (generated by figure1_behavior_calculate.m)
%
% OUTPUTS:
%   - Figure 1 panels (saved as vector graphics)
%
% Author: Nicholas E. Myers  
% Cleaned for GitHub: 2026
% For: Myers, Stokes, & Muhle-Karbe (2026) J. Neuroscience

clearvars;
close all;
clc;

%% 1. SETUP
paths = config();

% Find the most recent results file
results_pattern = fullfile(paths.results, 'Study12_Figure1_Behavior_Results_*.mat');
files = dir(results_pattern);
if isempty(files)
    error('No results file found matching: %s', results_pattern);
end

% Load most recent file
[~, idx] = max([files.datenum]);
results_file = fullfile(files(idx).folder, files(idx).name);
fprintf('Loading results from: %s\n', results_file);
load(results_file);

%% 2. PREPARE DATA

% Extract key variables
% (Assuming 'output' structure contains the results)
accuracy_switch = output.accuracy_switch;
accuracy_repeat1 = output.accuracy_repeat1;
accuracy_repeat2plus = output.accuracy_repeat2plus;

rt_switch = output.rt_switch;
rt_repeat1 = output.rt_repeat1;
rt_repeat2plus = output.rt_repeat2plus;

nsubs = size(accuracy_switch, 1);

%% 3. FIGURE 1A-B: EXAMPLE TRIAL SEQUENCE
% (Would show trial structure schematic - typically done in illustration software)

%% 4. FIGURE 1C: ACCURACY BY TRIAL TYPE

figure('Position', [100, 100, 400, 400]);
hold on;

% Plot individual subjects
x = [1 2 3];
for isub = 1:nsubs
    plot(x, [accuracy_switch(isub), accuracy_repeat1(isub), accuracy_repeat2plus(isub)], ...
        'o-', 'Color', [0.7 0.7 0.7], 'MarkerSize', 4);
end

% Plot group means
mean_acc = [mean(accuracy_switch), mean(accuracy_repeat1), mean(accuracy_repeat2plus)];
sem_acc  = [std(accuracy_switch), std(accuracy_repeat1), std(accuracy_repeat2plus)] / sqrt(nsubs);

errorbar(x, mean_acc, sem_acc, 'ko-', 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', 'k');

% Format
xlim([0.5 3.5]);
ylim([0.5 1.0]);
set(gca, 'XTick', 1:3, 'XTickLabel', {'Switch', 'Repeat 1', 'Repeat 2+'});
ylabel('Accuracy (proportion correct)');
xlabel('Trial Type');
title('Switch Cost in Accuracy');

% Add statistics
% (Would add significance stars based on t-tests)

%% 5. FIGURE 1D: REACTION TIME BY TRIAL TYPE

figure('Position', [550, 100, 400, 400]);
hold on;

% Plot individual subjects
for isub = 1:nsubs
    plot(x, [rt_switch(isub), rt_repeat1(isub), rt_repeat2plus(isub)], ...
        'o-', 'Color', [0.7 0.7 0.7], 'MarkerSize', 4);
end

% Plot group means
mean_rt = [mean(rt_switch), mean(rt_repeat1), mean(rt_repeat2plus)];
sem_rt  = [std(rt_switch), std(rt_repeat1), std(rt_repeat2plus)] / sqrt(nsubs);

errorbar(x, mean_rt, sem_rt, 'ko-', 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', 'k');

% Format
xlim([0.5 3.5]);
ylim([0.5 1.0]);
set(gca, 'XTick', 1:3, 'XTickLabel', {'Switch', 'Repeat 1', 'Repeat 2+'});
ylabel('Reaction Time (s)');
xlabel('Trial Type');
title('Switch Cost in RT');

%% 6. FIGURE 1E: PSYCHOMETRIC CURVES

% NOTE: This section would plot fitted psychometric curves
% showing the slope (precision) and asymptote (guess rate)
% for Switch vs. Repeat trials

% Pseudocode:
% - Plot probe offset vs. P(clockwise response)  
% - Overlay fitted psychometric function
% - Show separately for Switch and Repeat

%% 7. FIGURE 1F-G: ITEM DISTANCE EFFECTS

% NOTE: These panels show how accuracy/RT vary with
% the angular distance between the two memory items

% Pseudocode:
% - Extract item_distance and performance data
% - Fit linear regression
% - Plot data points with regression line
% - Show separately for Switch and Repeat

%% 8. SAVE FIGURES

% Save as vector graphics for publication
figures_dir = fullfile(paths.results, 'figures');
if ~exist(figures_dir, 'dir')
    mkdir(figures_dir);
end

% Example save commands:
% print(gcf, fullfile(figures_dir, 'Figure1C_Accuracy.pdf'), '-dpdf', '-vector');
% print(gcf, fullfile(figures_dir, 'Figure1C_Accuracy.svg'), '-dsvg');

fprintf('\n=== Plotting Complete! ===\n');
fprintf('Figures saved to: %s\n', figures_dir);

%% HELPER FUNCTIONS

function mean_val = nanmean(x, dim)
    % NANMEAN - Mean ignoring NaN values
    if nargin < 2
        dim = 1;
    end
    mean_val = mean(x, dim, 'omitnan');
end

function sem_val = nansem(x, dim)
    % NANSEM - Standard error of mean ignoring NaN values
    if nargin < 2
        dim = 1;
    end
    n = sum(~isnan(x), dim);
    sem_val = nanstd(x, [], dim) ./ sqrt(n);
end
