function [success] = SetupPlotting(fontsize)
%[success] = SetupPlotting(fontsize)
%success = 1: all good
%success = 0: something went wrong
if nargin <1
    fontsize = 12;
end
try
    % get the matlab version to identify the appropriate name for the
    % root figure object
    matlabversion = version('-release');
    if any(ismember(matlabversion,{'2012a' '2012b'}))
       rootname = 0;
       %set(rootname,'DefaultAxesFontName', 'Arial', ...
       %             'DefaultTextFontname', 'Arial');
    else
       rootname = groot;
       set(rootname,'DefaultAxesFontName', 'Helvetica', ...
                    'DefaultTextFontname', 'Helvetica');
    end
    % set the tickdirs to go out - need this specific order
    set(rootname, 'DefaultAxesTickDir', 'out');
    set(rootname, 'DefaultAxesTickDirMode', 'manual');

    % general graphics, this will apply to any figure you open (groot is the default figure object).
    % I have this in my startup.m file, so I don't have to retype these things whenever plotting a new fig.
    set(rootname, ...
        'DefaultFigureColorMap', linspecer, ...
        'DefaultFigureColor', 'w', ...
        'DefaultAxesLineWidth', 0.5, ...
        'DefaultAxesXColor', 'k', ...
        'DefaultAxesYColor', 'k', ...
        'DefaultAxesFontUnits', 'points', ...
        'DefaultAxesFontSize', fontsize, ...
        'DefaultLineLineWidth', 1, ...
        'DefaultTextFontUnits', 'Points', ...
        'DefaultTextFontSize', fontsize, ...
        'DefaultAxesBox', 'off', ...
        'DefaultAxesTickLength', [0.02 0.025]);
    success = true;
catch
    success = false;
end
end